### ISSUE TITLE
how to run my lua file

### ISSUE THREAD

**Issue by ZAA03** [leafo/gh-actions-lua#18]
The Full Example have a little problem.
And I use your github action，always show `lua: cannot open **.lua: No such file or directory` 
like this
```
name: test 
   on: [push] 
   jobs: 
 test: 
 runs-on: ubuntu-latest 
   steps: 
   - uses: leafo/gh-actions-lua@v8 
 with: 
 luaVersion: "5.1.5" 
 #5.1.5 
   - uses: leafo/gh-actions-luarocks@v4 

 - name:  install package
 run: | 
 luarocks install luasocket 
 luarocks install dkjson 
 luarocks install md5 

 - name: print package version
 run: | 
 lua -e 'http = require ("socket.http") print(socket._VERSION)' 
 lua -e 'md5 = require "md5" print(md5._VERSION)' 

#---------------------------------------------------------------
   - name: Run 
 run: | 
         pwd 
         lua ./***.lua                            #←----  Error in here！！
#---------------------------------------------------------------
```

It will show ` lua: cannot open **.lua: No such file or directory`
Run is error
**How can I solve this problem？**
