### ISSUE TITLE
Fails on windows-latest

### ISSUE THREAD

**Issue by telemachus** [leafo/gh-actions-lua#26]
I'm not able to get this to work on `windows-latest`. Because I thought that this might be my own fault, I tried using the `test.yml` file from #23, when Windows support was added. No joy. I've copied the YAML file that I used below as well as the error I'm seeing. I'll also leave a link to the failed logs, case that helps anyone.

```yaml
name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.4", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]
        machineTag: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build Lua
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: ${{ matrix.luaVersion }}
        buildCache: false

    - name: Test Lua
      run: lua -e "print('hi from lua')"

  test-cache:
    needs: test

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.4", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]
        machineTag: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.machineTag }}

    steps:
    - uses: actions/checkout@main

    - name: Get Lua from cache
      uses: './'
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: Test Lua
      run: lua -e "print('hi from lua')"
```

```log
[52] C:\Windows\system32\tar.exe xz -C .install -f D:\a\_temp\83df0290-9720-420f-8c0c-cfa228554404
[53](https://github.com/telemachus/split/actions/runs/3977171986/jobs/6818094584#step:4:54)
Error: Failed to install Lua: Error: Unable to locate executable file: sudo. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

[The failed job is here](https://github.com/telemachus/split/actions/runs/3977171986/jobs/6818094584) in case that helps. Let me know if you need any other information.

**Comment by magneto538** [comment]
Observing the same behaviour here with the following simple snippet:

```
jobs:
    tests:
      runs-on: windows-latest
      timeout-minutes: 10
      steps:
        - uses: actions/checkout@v3
  
        - uses: leafo/gh-actions-lua@v9
          with:
            luaVersion: "5.4"
  
        - uses: leafo/gh-actions-luarocks@v4
  
        - name: Install dependencies
          run: |
            luarocks install luafilesystem
```

**Comment by siffiejoe** [comment]
It seems that the code adding Windows support isn't released yet.

**Comment by alerque** [comment]
Try

```yaml
      uses: leafo/gh-actions-lua@master
```

**Comment by telemachus** [comment]
> Try
> 
> ```yaml
>       uses: leafo/gh-actions-lua@master
> ```

Yes, [that does the trick](https://github.com/telemachus/split/actions/runs/4054344884/jobs/6976064931). Thank you.

For anyone else having this problem, a workflow like the following should work:

```yaml
name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    name: split test (using lua ${{ matrix.luaVersion }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}
        buildCache: false
    - name: test
      run: |
        cd test
        bash runner.sh
```

Note that `uses: ilammy/msvc-dev-cmd@v1` is also essential. Probably everyone else will know this, but I forgot it the first time I tried. (I should probably use that only on Windows, but at least for the moment, it doesn't break Ubuntu or MacOS if you include it universally.)

I'm going to leave this issue open until `master` becomes `v10` unless someone suggests otherwise. That way, anyone with this problem can find a quick fix. Thanks to @alerque and @siffiejoe.
