### ISSUE TITLE
Linking step fails on Cygwin

### ISSUE THREAD

**Issue by dargueta** [leafo/gh-actions-lua#27]
CI YAML
```yaml
testing_cygwin:
  runs-on: windows-latest
  # ...
  steps:
    # https://github.com/marketplace/actions/install-cygwin-action#line-endings
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3
    - uses: cygwin/cygwin-install-action@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.lua-version }}
```

Building fails on the linking step:
```
C:\cygwin\bin\link.exe /nologo /DLL /out:lua54.dll lapi.obj lauxlib.obj lbaselib.obj ...(etc)
/usr/bin/link: extra operand '/out:lua54.dll'
```

My guess is that this should be treating this like GCC instead, and passing the usual *NIX-like arguments.
```
-shared -o lua54.dll lapi.obj ...
```
