### ISSUE TITLE
LuaJIT.org 404 when downloading tarball

### ISSUE THREAD

**Issue by benwilber** [leafo/gh-actions-lua#49]
It appears that LuaJIT.org has [stopped publishing release tarballs on their website.](https://luajit.org/download.html)

> **No Release Tarballs or Binaries**
> LuaJIT uses **rolling releases**. There are no release tarballs available for download.
>
> Please do not use obsolete versions from older tarballs or zip files. Please remove any outdated links to these downloads — these links will cease to work soon. 

See: https://github.com/leafo/gh-actions-lua/blob/master/main.js#L89

In the meantime, I've just switched to testing against OpenResty's LuaJIT distribution.

**Comment by harrisoncramer** [comment]
Hey Ben, what's the fix you went with to solve this? I've got this in my actions file, is there an easy fix or can you recommend an alternative action?

```yaml
      - name: Install luajit
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"
```
