### ISSUE TITLE
The example for building busted fails - nlua not found

### ISSUE THREAD

**Issue by ColinKennedy** [leafo/gh-actions-lua#53]
See https://github.com/ColinKennedy/nvim-best-practices-plugin-template/actions/runs/10969773023

```
Run busted -o utfTerminal
  busted -o utfTerminal
  shell: /usr/bin/bash -e {0}
  env:
    MSYS: winsymlinks:nativestrict
    LUA_PATH: ;;/home/runner/.luarocks/share/lua/5.1/?.lua;/home/runner/.luarocks/share/lua/5.1/?/init.lua;/home/runner/work/nvim-best-practices-plugin-template/nvim-best-practices-plugin-template/.luarocks/share/lua/5.1/?.lua;/home/runner/work/nvim-best-practices-plugin-template/nvim-best-practices-plugin-template/.luarocks/share/lua/5.1/?/init.lua
    LUA_CPATH: ;;/home/runner/.luarocks/lib/lua/5.1/?.so;/home/runner/work/nvim-best-practices-plugin-template/nvim-best-practices-plugin-template/.luarocks/lib/lua/5.1/?.so
sh: 1: nlua: not found
Error: Process completed with exit code 1.
```

This is reproducible with the "Full Example" in this repo's README

```yaml
name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v4

    - name: build
      run: |
        luarocks install busted
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal
```

It could be an issue with busted or with this GItHub action. Some clarity would be appreciated.
