### ISSUE TITLE
Can't install Lua 5.1+ on windows

### ISSUE THREAD

**Issue by Lautenschlager-id** [leafo/gh-actions-lua#6]
![image](https://user-images.githubusercontent.com/26045253/68803050-e43a0200-063d-11ea-96f2-a9554e653eb5.png)

Example:
```YML
name: test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3"]

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: test
      run: lua test.lua
```
